# Generated by Django 2.2 on 2019-11-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(default=0)),
                ('type', models.BooleanField(choices=[(True, 'news'), (False, 'activity')])),
                ('content', models.CharField(default='', max_length=500)),
                ('title', models.CharField(default='', max_length=200)),
                ('abstract', models.CharField(default='', max_length=250)),
                ('images', models.CharField(default='', max_length=500)),
                ('status', models.BooleanField()),
                ('create_time', models.DateField()),
                ('visits', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('member_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('logo', models.CharField(default='', max_length=50)),
                ('member_status', models.IntegerField(default=0)),
            ],
        ),
    ]
