# Generated by Django 2.2 on 2019-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='qq',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='wechat',
            field=models.CharField(default='', max_length=25),
        ),
    ]
