# Generated by Django 2.2 on 2020-02-27 12:16

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20191113_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='type',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='status',
            field=models.BooleanField(choices=[(True, '会员'), (False, '非会员')]),
        ),
    ]
