# Generated by Django 2.2 on 2020-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20200227_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='images',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='status',
            field=models.BooleanField(choices=[(True, '会员'), (False, '非会员')], default=False),
        ),
    ]
