# Generated by Django 2.2 on 2019-11-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('images', models.CharField(default='', max_length=500)),
                ('abstract', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=200)),
                ('like', models.IntegerField(default=0)),
                ('share', models.IntegerField(default=0)),
                ('cultureId', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('quantity', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
            ],
        ),
    ]
