# Generated by Django 2.2 on 2019-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='create',
            field=models.DateField(auto_now=True),
        ),
    ]
