# Generated by Django 2.2 on 2020-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200227_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
